export = {
  parser: "@typescript-eslint/parser",
  parserOptions: {
    sourceType: "module",
    emcaFeatures: {
      jsx: true
    },
    project: process.cwd() + '/tsconfig.json'
  },
  plugins: ["@typescript-eslint/eslint-plugin", "import", "sort-export-all"],
  extends: [
    "next",
    "turbo",
    "plugin:prettier/recommended",
    "plugin:@typescript-eslint/eslint-recommended",
    "lunde",
  ],
  settings: {
    "import/extensions": [".js", ".jsx", ".ts", ".tsx"],
    "import/ignore": ["\\.json$", "\\.(scss|less|css|styl)$"],
    "import/internal-regex": "^S(@/.*$)",
    "import/resolver": {
      typescript: {
        project: process.cwd() + '/tsconfig.json',
      },
    },
  },
  env: {
    node: true,
  },
  rules: {
    "@next/next/no-html-link-for-pages": "off",
    // Typescript
    "@typescript-eslint/ban-ts-comment": "off",
    "@typescript-eslint/ban-ts-ignore": "off",
    "@typescript-eslint/ban-types": "error",
    "@typescript-eslint/camelcase": "off",
    "@typescript-eslint/explicit-function-return-type": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/interface-name-prefix": "off",
    "@typescript-eslint/member-delimiter-style": "off",
    "@typescript-eslint/no-explicit-any": "off",
    "@typescript-eslint/no-unused-vars": "error",
    "@typescript-eslint/no-use-before-define": "off",
    "@typescript-eslint/no-empty-function": "off",
    "@typescript-eslint/no-empty-interface": "off",
    "@typescript-eslint/prefer-ts-expect-error": "warn",
    "@typescript-eslint/no-shadow": "warn",
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/consistent-type-imports": [
      "warn",
      {
        prefer: "type-imports",
      },
    ],
    "@typescript-eslint/no-this-alias": "error",
    "@typescript-eslint/return-await": ["warn", "always"],

    "react/jsx-key": "off",

    "default-case-last": "warn",
    "dot-notation": "warn",
    "func-name-matching": "warn",
    "func-style": ["warn", "declaration"],
    // "no-case-declarations": "off",
    "no-console": ["error", { allow: ["warn", "error"] }],
    // "no-empty-pattern": "off",
    // "no-constant-condition": "off",
    "no-lonely-if": "warn",
    // "no-prototype-builtins": "off",
    "no-self-compare": "warn",
    "no-unreachable-loop": "warn",
    // "require-atomic-updates": "warn",
    // "prefer-arrow-callback": ["warn", { allowNamedFunctions: true }],
    // autofix - just warn
    "sort-export-all/sort-export-all": "warn",
    "prettier/prettier": "warn",
    // should be off for typescript-eslint
    "no-unused-vars": "off",
    "no-return-await": "off",

    /** import */
    "import/default": "off",
    "import/export": "error",
    "import/named": "off",
    "import/namespace": "error",
    "import/no-extraneous-dependencies": "error",
    "import/no-named-as-default-member": "off",
    "import/no-cycle": "warn",
    "import/no-self-import": "error",
    "import/no-useless-path-segments": "off",
    "import/extensions": "warn",
    "import/newline-after-import": "off",
    "import/no-named-as-default": "warn",
    "import/no-amd": "error",
    "import/no-commonjs": "off",
    "import/no-named-default": "warn",
    "import/no-namespace": "off",
    "import/no-nodejs-modules": "off",
    "import/order": [
      "warn",
      {
        "newlines-between": "always",
        pathGroups: [
          {
            pattern: "@kerk/**",
            group: "internal",
          },
          {
            pattern:
              "{express,jest,knex,objection,prisma,nest,next,nexus,react,vitest}",
            group: "builtin",
            position: "before",
          },
        ],
        pathGroupsExcludedImportTypes: [
          "express",
          "jest",
          "knex",
          "objection",
          "prisma",
          "nest",
          "next",
          "nexus",
          "react",
          "vitest",
        ],
        groups: [
          "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index",
          "object",
        ],
        alphabetize: {
          order: "asc",
          caseInsensitive: true,
        },
      },
    ],
    "sort-imports": [
      "warn",
      {
        ignoreDeclarationSort: true,
        ignoreMemberSort: false,
      },
    ],
    "import/first": "error",
    // "import/no-anonymous-default-export": "off",
    "import/no-absolute-path": "error",
    "import/no-deprecated": "error",
    "import/no-duplicates": "error",
    "import/no-internal-modules": "off",
    "import/no-mutable-exports": "warn",
    "import/no-restricted-paths": "off",
    "import/no-unassigned-import": "off",
    "import/no-webpack-loader-syntax": "error",
    "import/no-unused-modules": "off",
    "import/max-dependencies": "off",
    "import/dynamic-import-chunkname": "off",
    "import/exports-last": "off",
    "import/group-exports": "off",
    "import/no-dynamic-require": "off",
    "import/prefer-default-export": "off",
    "import/no-default-export": "warn",
    "import/no-named-export": "off",
    "import/unambiguous": "off",
    "import/no-relative-parent-imports": "off",
    "global-require": "off",

  },
}
